// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIq7VZ4phXLoSrcTr_0-10S1KDqMAw3uE',
    appId: '1:908869411323:web:76fc9dbe6a7aa047a52b5e',
    messagingSenderId: '908869411323',
    projectId: 'vocab-ai-2ff78',
    authDomain: 'vocab-ai-2ff78.firebaseapp.com',
    storageBucket: 'vocab-ai-2ff78.firebasestorage.app',
    measurementId: 'G-7ET08724JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0KHtdfYhncKjga1VcOGOJKM6Tp-95S4',
    appId: '1:908869411323:android:f28c7a002ae850fea52b5e',
    messagingSenderId: '908869411323',
    projectId: 'vocab-ai-2ff78',
    storageBucket: 'vocab-ai-2ff78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhtTEJhISXS5B7ftSBcHIL0Q4NPjdx8yc',
    appId: '1:908869411323:ios:8afca4db1fc36faba52b5e',
    messagingSenderId: '908869411323',
    projectId: 'vocab-ai-2ff78',
    storageBucket: 'vocab-ai-2ff78.firebasestorage.app',
    iosClientId: '908869411323-m0sqmpmr2qv1nfed2dq71krs76er9kp9.apps.googleusercontent.com',
    iosBundleId: 'com.vocabai.vocabAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhtTEJhISXS5B7ftSBcHIL0Q4NPjdx8yc',
    appId: '1:908869411323:ios:8afca4db1fc36faba52b5e',
    messagingSenderId: '908869411323',
    projectId: 'vocab-ai-2ff78',
    storageBucket: 'vocab-ai-2ff78.firebasestorage.app',
    iosClientId: '908869411323-m0sqmpmr2qv1nfed2dq71krs76er9kp9.apps.googleusercontent.com',
    iosBundleId: 'com.vocabai.vocabAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIq7VZ4phXLoSrcTr_0-10S1KDqMAw3uE',
    appId: '1:908869411323:web:0a06d6a20f5142cfa52b5e',
    messagingSenderId: '908869411323',
    projectId: 'vocab-ai-2ff78',
    authDomain: 'vocab-ai-2ff78.firebaseapp.com',
    storageBucket: 'vocab-ai-2ff78.firebasestorage.app',
    measurementId: 'G-J5FXML1KQK',
  );
}
